"""empty message

Revision ID: b8ddec9f218d
Revises: ef0a73754306
Create Date: 2022-04-17 23:07:51.786475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ddec9f218d'
down_revision = 'ef0a73754306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adv_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adv_model_description'), 'adv_model', ['description'], unique=True)
    op.create_index(op.f('ix_adv_model_header'), 'adv_model', ['header'], unique=True)
    op.create_index(op.f('ix_adv_model_owner'), 'adv_model', ['owner'], unique=True)
    op.drop_index('ix_user_model_email', table_name='user_model')
    op.drop_index('ix_user_model_username', table_name='user_model')
    op.drop_table('user_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_model_pkey')
    )
    op.create_index('ix_user_model_username', 'user_model', ['username'], unique=False)
    op.create_index('ix_user_model_email', 'user_model', ['email'], unique=False)
    op.drop_index(op.f('ix_adv_model_owner'), table_name='adv_model')
    op.drop_index(op.f('ix_adv_model_header'), table_name='adv_model')
    op.drop_index(op.f('ix_adv_model_description'), table_name='adv_model')
    op.drop_table('adv_model')
    # ### end Alembic commands ###
